### ISSUE TITLE
Inquiry: Ability of action to handle concurrency

### ISSUE THREAD

**Issue by opike** [niteoweb/reviewapps-deploy-status#15]
Hi,
I'm currently using this action in my CI process and I'm trying to determine it's ability to handle two heroku deployments from two different PRs that are occurring concurrently. From doing a static read-through of the code, it looks like there's a potential for a collision. Is this correct or am I missing something? Thanks.

**Comment by suryasr007** [comment]
No. It doesn't collide. Because different process will run in different GitHub Runners. 

Eg: 
![image](https://user-images.githubusercontent.com/10533926/113249688-be69d780-92dc-11eb-898e-c6bb99e003dc.png)


The same action runs on different PRs in parallel.
