### ISSUE TITLE
Do you output the URL for the review app?

### ISSUE THREAD

**Issue by tomatau** [niteoweb/reviewapps-deploy-status#5]
I can't find a convenient way to access the PR number in the workflow yml so that I can build the review app's URL and point my browser tests at it. Do you expose the review app's URL as I can see you already have access to it in the action. It would be useful to expose some outputs from the steps using your action.

**Comment by suryasr007** [comment]
> I can see you already have access to it in the action.

Yes. I fetch it from deployments API.

> It would be useful to expose some outputs from the steps using your action.

Sure. Thanks for the suggestion.

**Comment by tomatau** [comment]
Anyone with the same concern, I've found that it can be accessed like this:

```
https://$HEROKU_APP_NAME-pr-${{ github.event.number }}.herokuapp.com/
```

But this is still fragile and would be better to use the full app name in an output

**Comment by suryasr007** [comment]
>Anyone with the same concern, I've found that it can be accessed like this: 
https://$HEROKU_APP_NAME-pr-${{ github.event.number }}.herokuapp.com/
But this is still fragile and would be better to use the full app name in an output

The current version of Heroku review-apps uses this naming scheme. But this is not the case with [next version](https://devcenter.heroku.com/articles/review-apps-beta#review-app-names). Hence, I used Github Deployments API.

**Comment by tomatau** [comment]
> The current version of Heroku review-apps uses this naming scheme. But this is not the case with [next version](https://devcenter.heroku.com/articles/review-apps-beta#review-app-names). Hence, I used Github Deployments API.

Yes exactly, the name is fragile and would be much better to use `output` from this action to determine the app name in other steps.
