### ISSUE TITLE
Possible to return a Review App Environment Variable?

### ISSUE THREAD

**Issue by patrickmichalina** [niteoweb/reviewapps-deploy-status#9]
Would love the Postgres connection for a review app sent back to github action to use in another task if possible? I am not super familiar with github actions and their limitations, think this is possible?

**Comment by mathieutu** [comment]
Hi, 
It could be cool to have at least the app name, to be allow to execute commands with heroku cli, or do other things from it on our own.

**Comment by patrickmichalina** [comment]
@mathieutu  yeah anything to be able for Github actions to know about the current Review App in order to say run e2e test or other things against that ephemeral environment.

**Comment by suryasr007** [comment]
@patrickmichalina 

With the current implementation of the action (*to support both old and review apps*) it is not possible as the action uses GitHub API to fetch the Review App status.

However, if you are using a new version of the Review App, you can utilize the [Review App API](https://devcenter.heroku.com/articles/github-integration-review-apps#review-apps-api) to fetch the metadata of the Review App.

**Comment by suryasr007** [comment]
@mathieutu 

Do you mean Review App name? If so, the name can be extracted from the `outputs.review_app_url`. The format of the URL is  `<REVIEWAPP_NAME>.herokuapp.com`.

**Comment by mathieutu** [comment]
Yeah it's what I'm doing for now. But it's a bit too bad to have it in your action, concatenate it with herokuapp.com, to let us later do the opposite process. 🙂

And @patrickmichalina we have access to the heroku cli in the basic ubuntu image of github action, so with the name of the app, you can get anything you want.

**Comment by patrickmichalina** [comment]
@mathieutu I was not aware I could do that, thank you!
